"""initial nutrition tables

Revision ID: 31f46cb5633c
Revises: 
Create Date: 2026-09-12 20:36:03.358485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f46cb5633c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_day',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_nutrition_date')
    )
    op.create_index(op.f('ix_nutrition_day_user_id'), 'nutrition_day', ['user_id'], unique=False)
    op.create_table('food_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity_label', sa.String(length=60), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['nutrition_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_entry')
    op.drop_index(op.f('ix_nutrition_day_user_id'), table_name='nutrition_day')
    op.drop_table('nutrition_day')
    # ### end Alembic commands ###
