"""add water_ml to nutrition_day

Revision ID: 722ee768e24a
Revises: 31f46cb5633c
Create Date: 2026-09-12 20:53:33.228809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722ee768e24a'
down_revision: Union[str, None] = '31f46cb5633c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: server_default so
    # existing rows backfill to 0 instead of violating the NOT NULL add ###
    op.add_column(
        'nutrition_day', sa.Column('water_ml', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition_day', 'water_ml')
    # ### end Alembic commands ###
