# Generated by Django 6.0.7 on 2026-07-25 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreakState',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_logged_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyVolumeSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('volume', models.FloatField(default=0)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'date'), name='unique_user_date_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('exercise_name', models.CharField(max_length=120)),
                ('best_weight', models.FloatField()),
                ('best_reps', models.PositiveIntegerField()),
                ('best_date', models.DateField()),
                ('previous_weight', models.FloatField(blank=True, null=True)),
                ('trend', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('same', 'same')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-best_date'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_name'), name='unique_user_exercise_pr')],
            },
        ),
    ]
