# Generated by Django 6.0.7 on 2026-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='last_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='last_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
