# Generated by Django 6.0.7 on 2026-07-25 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_personalrecord_last_date_personalrecord_last_reps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseDailyBest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('exercise_name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('reps', models.PositiveIntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'exercise_name', 'date'), name='unique_user_exercise_date_best')],
            },
        ),
    ]
