# Generated by Django 6.0.7 on 2026-09-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_exercisedailybest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyvolumesnapshot',
            name='tag',
        ),
    ]
