# Generated by Django 6.0.7 on 2026-09-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workoutday_tag_customtag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customtag',
            name='unique_user_custom_tag_name',
        ),
        migrations.DeleteModel(
            name='CustomTag',
        ),
        migrations.RemoveField(
            model_name='exerciselibraryitem',
            name='primary_tag',
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='tag',
        ),
        migrations.AddField(
            model_name='exerciselibraryitem',
            name='category',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='exerciselibraryitem',
            name='is_bodyweight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
