# Generated by Django 6.0.7 on 2026-09-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_customtag_unique_user_custom_tag_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio')], default='strength', max_length=20),
        ),
        migrations.AddField(
            model_name='setentry',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='setentry',
            name='duration_minutes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='setentry',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
