# Generated by Django 6.0.7 on 2026-07-25 06:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('fcm_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('failed', 'failed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderPreference',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('days_of_week', models.JSONField(default=list)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
            ],
        ),
    ]
