# Generated by Django 6.0.7 on 2026-07-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderpreference',
            name='last_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
